############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESOURSE"
url = "resource/"
weight = 4

[[main]]
name = "NEWS"
weight = 5



[[main]]
name = "VARIETIES"
url = "varieties/"
weight = 3


[[main]]
name = "GENOME"
url = "genome/"
weight = 2


[[main]]
name = "LITERATURE"
url = "exam/"
weight = 6


[[main]]
parent = "NEWS"
name = "小麦产量"
url = "yield/"


[[main]]
parent = "NEWS"
name = "抗病抗旱"
url = "resistance/"


[[main]]
parent = "NEWS"
name = "生长发育"
url = "growth/"


[[main]]
parent = "NEWS"
name = "遗传研究"
url = "genetic/"


[[main]]
parent = "NEWS"
name = "中英文文献汇总"
url = "assemble/"