############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESUORSE"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "L&V"
hasChildren = true

[[main]]
name = "NEWS"
url = "news/"
weight = 4

[[main]]
parent = "L&V"
name = "LITERATURE"
url = "Literature/"


[[main]]
parent = "L&V"
name = "VARIETIES"
url = "varieties/"