############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESUORSE"
url = "about/"
weight = 2

[[main]]
name = "NEWS"
url = "news/"
weight = 4

[[main]]
name = "VARIETIES"
url = "varieties/"
weight = 3 

[[main]]
name = "LITERATURE"
url = "Literature/"
weight = 3 