############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESOURSE"
url = "about/"
weight = 5

[[main]]
name = "NEWS"
url = "news/"
weight = 6

[[main]]
name = "LITERATURE"
url = "Literature/"
weight = 4


[[main]]
name = "VARIETIES"
url = "varieties/"
weight = 2


[[main]]
name = "GENOME"
url = "genome/"
weight = 3