############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESOURSE"
url = "resource/"
weight = 5

[[main]]
name = "NEWS"
weight = 6
hasChildren = true



[[main]]
name = "VARIETIES"
url = "varieties/"
weight = 2


[[main]]
name = "GENOME"
url = "genome/"
weight = 3


[[main]]
name = "LITERATURE"
url = "exam/"
weight = 4


[[main]]
parent = "NEWS"
name = "Yield"
url = "Yield/"


[[main]]
parent = "NEWS"
name = "Disease and drought resistance"
url = "Disease and drought resistance/"


[[main]]
parent = "NEWS"
name = "Growth and development"
url = "Growth and development/"


[[main]]
parent = "NEWS"
name = "Genetic research"
url = "Genetic research/"


[[main]]
parent = "NEWS"
name = "Comprehensive literature"
url = "Comprehensive literature/"