############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Resource"
url = "about/"
weight = 2

[[main]]
name = "News"
url = "news/"
weight = 3

# footer menu
[[footer]]
name = "Resource"
url = "about/"
weight = 1

[[footer]]
name = "News"
url = "news/"
weight = 2
