############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESUOSE"
url = "about/"
weight = 2

[[main]]
name = "NEWS"
url = "news/"
weight = 3

