############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "RESOURSE"
url = "resource/"
weight = 5

[[main]]
name = "NEWS"
weight = 6
hasChildren = true



[[main]]
name = "VARIETIES"
url = "varieties/"
weight = 2


[[main]]
name = "GENOME"
url = "genome/"
weight = 3


[[main]]
name = "LITERATURE"
url = "exam/"
weight = 4


[[main]]
parent = "NEWS"
name = "产量"
url = "小麦产量/"


[[main]]
parent = "NEWS"
name = "抗病抗旱"
url = "抗病抗旱/"


[[main]]
parent = "NEWS"
name = "生长发育"
url = "生长发育/"


[[main]]
parent = "NEWS"
name = "遗传研究"
url = "遗传研究/"


[[main]]
parent = "NEWS"
name = "中英文文献汇总"
url = "中英文文献汇总/"